### ISSUE TITLE
A very big problem

### ISSUE THREAD

**Issue by Mishatopkek** [PashaYakubovsky/aggregator#1]
I just wanted to take a moment to say how much I enjoy using aggregator. It has been incredibly useful to me, and I appreciate the thought and effort that went into its development.
Thank you Pasha for your hard work in creating such a great product!

<img src="https://media1.giphy.com/media/3o7qE7iHUUPHfV7xQI/giphy.gif"/>

**Comment by pashaydev** [comment]
![0wb5ky1n0zpd1](https://github.com/user-attachments/assets/2d27c0a9-d540-486d-a530-382583a4719b)
@Mishatopkek Thank you so much, i was inspired by reading this beautiful book.

**Comment by Mishatopkek** [comment]
Thank you for a masterpiece 🙏😊!
